/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uva.ipc.vista;

import java.util.*;
import java.text.SimpleDateFormat;
import com.formdev.flatlaf.*;
import com.formdev.flatlaf.intellijthemes.*;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.*;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.*;
import java.time.*;
import javax.swing.*;
import uva.ipc.controlador.Controlador;
import uva.ipc.modelo.Viaje;

/**
 * @author Daniel Garcia Solla
 * @author Carolina de las Heras Clavier 
 */
public class Vista extends javax.swing.JFrame {

    private Controlador controlador;
    private DefaultListModel<Viaje> viajesListModel = new DefaultListModel<>();
    private boolean darkTheme = false;

    /**
     * Creates new form MainFrame
     */
    public Vista() {
        FlatLaf.setup(new FlatAtomOneLightIJTheme());

        initComponents();
        this.setLocationRelativeTo(null);
        this.controlador = new Controlador(this);
        rutasList.setModel(viajesListModel);
        setMinimumSize(new Dimension(650, 700));
        desactivarPinTarjeta();
        inicializarIconos();
        limpiar();

        tarjetaCreditoButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                controlador.tarjetaCreditoStart();
            }

            @Override
            public void mouseExited(MouseEvent e) {
                controlador.tarjetaCreditoStop();
            }
        });

        tarjetaCylButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                controlador.tarjetaCylStart();
            }

            @Override
            public void mouseExited(MouseEvent e) {
                controlador.tarjetaCylStop();
            }
        });
        styleButtons();
    }

    public void styleButtons() {
        styleButton(continuarPaso1Button);
        styleButton(continuarPaso2Button);
        styleButton(comprarOtroBillete);
        styleButton(aceptarButton);
    }

    public void styleButton(JButton button) {
        button.setBackground(UIManager.getColor("Component.accentColor"));
        if (darkTheme) {
            button.setForeground(UIManager.getColor("Label.foreground"));
        } else {
            button.setForeground(UIManager.getColor("Label.background"));
        }

    }

    public void inicializarIconos() {
        setObjectIcon(intercambiarEstacionesButton, "src/main/resources/Swap.png");
        setObjectIcon(tarjetaCreditoButton, "src/main/resources/Visa.png");
        setObjectIcon(tarjetaCylButton, "src/main/resources/Tarjetacyl.png");
    }

    public void setObjectIcon(JButton button, String path) {
        ImageIcon icon = new ImageIcon(path);
        Image img = icon.getImage().getScaledInstance(button.getWidth(), button.getHeight(), Image.SCALE_AREA_AVERAGING);
        ImageIcon ic = new ImageIcon(img);
        button.setIcon(ic);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        paso1Panel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        paso1Label = new javax.swing.JLabel();
        seleccioneEstacionLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        estacionOrigenSelector = new javax.swing.JComboBox<>();
        intercambiarEstacionesButton = new javax.swing.JButton();
        estacionDestinoSelector = new javax.swing.JComboBox<>();
        fechaDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jPanel5 = new javax.swing.JPanel();
        continuarPaso1Button = new javax.swing.JButton();
        cambiarTemaButton = new javax.swing.JButton();
        paso2Panel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        paso1Label1 = new javax.swing.JLabel();
        seleccioneEstacionLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        rutasList = new org.jdesktop.swingx.JXList();
        jPanel8 = new javax.swing.JPanel();
        bicicletaCheckBox = new javax.swing.JCheckBox();
        mascotaCheckBox = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        volver2Button = new javax.swing.JButton();
        continuarPaso2Button = new javax.swing.JButton();
        erroresLabel2 = new org.jdesktop.swingx.JXLabel();
        paso4Panel = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        paso1Label3 = new javax.swing.JLabel();
        comprarOtroBillete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dinoPanel = new javax.swing.JEditorPane();
        paso3Panel = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        paso1Label2 = new javax.swing.JLabel();
        seleccioneEstacionLabel2 = new javax.swing.JLabel();
        tarjetaCylRadioButton = new javax.swing.JRadioButton();
        tarjetaCreditoRadioButton = new javax.swing.JRadioButton();
        opcionesPanel = new javax.swing.JPanel();
        tarjetaCreditoPanel = new javax.swing.JPanel();
        tarjetaCreditoButton = new org.jdesktop.swingx.JXButton();
        pinTarjetaCreditoPanel = new javax.swing.JPanel();
        seleccioneEstacionLabel3 = new javax.swing.JLabel();
        pinTarjetaField = new javax.swing.JPasswordField();
        aceptarButton = new javax.swing.JButton();
        erroresLabel3 = new org.jdesktop.swingx.JXLabel();
        tarjetaCylPanel = new javax.swing.JPanel();
        tarjetaCylButton = new org.jdesktop.swingx.JXButton();
        erroresLabel4 = new org.jdesktop.swingx.JXLabel();
        jPanel11 = new javax.swing.JPanel();
        volver3Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tren Castilla y León");
        getContentPane().setLayout(new java.awt.CardLayout());

        paso1Panel.setEnabled(false);
        paso1Panel.setMaximumSize(new java.awt.Dimension(700, 700));
        paso1Panel.setMinimumSize(new java.awt.Dimension(600, 600));
        paso1Panel.setPreferredSize(new java.awt.Dimension(600, 600));
        paso1Panel.setLayout(new javax.swing.BoxLayout(paso1Panel, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        paso1Label.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        paso1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paso1Label.setText("Paso 1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(66, 247, 0, 0);
        jPanel2.add(paso1Label, gridBagConstraints);

        seleccioneEstacionLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        seleccioneEstacionLabel.setText("Seleccione las estaciones");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 227, 35, 212);
        jPanel2.add(seleccioneEstacionLabel, gridBagConstraints);

        paso1Panel.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        estacionOrigenSelector.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        estacionOrigenSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estacionOrigenSelectorActionPerformed(evt);
            }
        });
        estacionOrigenSelector.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                estacionOrigenSelectorPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(53, 166, 0, 0);
        jPanel3.add(estacionOrigenSelector, gridBagConstraints);

        intercambiarEstacionesButton.setBackground(new java.awt.Color(0, 0, 0, 0));
        intercambiarEstacionesButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        intercambiarEstacionesButton.setBorder(null);
        intercambiarEstacionesButton.setMaximumSize(new java.awt.Dimension(300, 300));
        intercambiarEstacionesButton.setMinimumSize(new java.awt.Dimension(200, 200));
        intercambiarEstacionesButton.setPreferredSize(new java.awt.Dimension(300, 300));
        intercambiarEstacionesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intercambiarEstacionesButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = -254;
        gridBagConstraints.ipady = -263;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(68, 12, 0, 0);
        jPanel3.add(intercambiarEstacionesButton, gridBagConstraints);

        estacionDestinoSelector.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 166, 0, 0);
        jPanel3.add(estacionDestinoSelector, gridBagConstraints);

        fechaDatePicker.setDate(new java.util.Date());
        fechaDatePicker.setDoubleBuffered(true);
        fechaDatePicker.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 52;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(44, 166, 41, 203);
        jPanel3.add(fechaDatePicker, gridBagConstraints);
        fechaDatePicker.setFormats(new SimpleDateFormat("dd/MM/yyyy"));
        fechaDatePicker.getMonthView().setFirstDayOfWeek(Calendar.MONDAY);
        fechaDatePicker.getMonthView().setLowerBound(new Date());

        paso1Panel.add(jPanel3);

        jPanel5.setLayout(new java.awt.GridBagLayout());

        continuarPaso1Button.setBackground(UIManager.getColor("Component.accentColor"));
        continuarPaso1Button.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        continuarPaso1Button.setText("Continuar");
        continuarPaso1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarPaso1ButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(132, 371, 0, 19);
        jPanel5.add(continuarPaso1Button, gridBagConstraints);

        cambiarTemaButton.setText("Tema Oscuro");
        cambiarTemaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarTemaButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 43;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(114, 21, 17, 0);
        jPanel5.add(cambiarTemaButton, gridBagConstraints);

        paso1Panel.add(jPanel5);

        getContentPane().add(paso1Panel, "card2");

        paso2Panel.setEnabled(false);
        paso2Panel.setMaximumSize(new java.awt.Dimension(700, 700));
        paso2Panel.setMinimumSize(new java.awt.Dimension(600, 600));
        paso2Panel.setPreferredSize(new java.awt.Dimension(600, 600));
        paso2Panel.setLayout(new java.awt.GridLayout(4, 1));

        jPanel6.setLayout(new java.awt.GridBagLayout());

        paso1Label1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        paso1Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paso1Label1.setText("Paso 2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(49, 243, 0, 241);
        jPanel6.add(paso1Label1, gridBagConstraints);

        seleccioneEstacionLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        seleccioneEstacionLabel1.setText("Selecciona tu tren");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 243, 36, 0);
        jPanel6.add(seleccioneEstacionLabel1, gridBagConstraints);

        paso2Panel.add(jPanel6);

        DefaultListModel<String> listModel = new DefaultListModel<>();
        rutasList.setModel(listModel);
        jScrollPane2.setViewportView(rutasList);

        jPanel7.add(jScrollPane2);

        paso2Panel.add(jPanel7);

        bicicletaCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bicicletaCheckBox.setText("Bicicleta");
        bicicletaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bicicletaCheckBoxActionPerformed(evt);
            }
        });

        mascotaCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mascotaCheckBox.setText("Mascota");
        mascotaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mascotaCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(264, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bicicletaCheckBox)
                    .addComponent(mascotaCheckBox))
                .addGap(261, 261, 261))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(bicicletaCheckBox)
                .addGap(6, 6, 6)
                .addComponent(mascotaCheckBox)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        paso2Panel.add(jPanel8);

        jPanel9.setLayout(new java.awt.GridBagLayout());

        volver2Button.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        volver2Button.setText("Volver");
        volver2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver2ButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(53, 40, 31, 0);
        jPanel9.add(volver2Button, gridBagConstraints);

        continuarPaso2Button.setBackground(UIManager.getColor("Component.accentColor"));
        continuarPaso2Button.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        continuarPaso2Button.setText("Continuar");
        continuarPaso2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarPaso2ButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(53, 370, 31, 30);
        jPanel9.add(continuarPaso2Button, gridBagConstraints);

        erroresLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        erroresLabel2.setText("Seleccione usted");
        erroresLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 430;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 40, 0, 30);
        jPanel9.add(erroresLabel2, gridBagConstraints);

        paso2Panel.add(jPanel9);

        getContentPane().add(paso2Panel, "card3");

        paso4Panel.setEnabled(false);
        paso4Panel.setMaximumSize(new java.awt.Dimension(700, 700));
        paso4Panel.setMinimumSize(new java.awt.Dimension(600, 600));
        paso4Panel.setPreferredSize(new java.awt.Dimension(600, 600));
        paso4Panel.setLayout(new java.awt.GridBagLayout());

        paso1Label3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        paso1Label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paso1Label3.setText("Pago confirmado");

        comprarOtroBillete.setBackground(UIManager.getColor("Component.accentColor"));
        comprarOtroBillete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comprarOtroBillete.setText("Comprar otro billete");
        comprarOtroBillete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarOtroBilleteActionPerformed(evt);
            }
        });

        try{
            dinoPanel.setEditable(false);
            dinoPanel.setPage("https://dinorunner.com/");
        }catch(Exception e){}
        jScrollPane1.setViewportView(dinoPanel);
        jScrollPane1.setPreferredSize(new Dimension(100,100));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(paso1Label3))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(comprarOtroBillete, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(paso1Label3)
                .addGap(37, 37, 37)
                .addComponent(comprarOtroBillete, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        paso4Panel.add(jPanel12, new java.awt.GridBagConstraints());

        getContentPane().add(paso4Panel, "card4");

        paso3Panel.setEnabled(false);
        paso3Panel.setMaximumSize(new java.awt.Dimension(700, 700));
        paso3Panel.setMinimumSize(new java.awt.Dimension(600, 600));
        paso3Panel.setPreferredSize(new java.awt.Dimension(600, 600));
        paso3Panel.setLayout(new javax.swing.BoxLayout(paso3Panel, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel10.setLayout(new java.awt.GridBagLayout());

        paso1Label2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        paso1Label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paso1Label2.setText("Paso 3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 227, 0, 0);
        jPanel10.add(paso1Label2, gridBagConstraints);

        seleccioneEstacionLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        seleccioneEstacionLabel2.setText("Selecciona el método de pago");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 188, 0, 221);
        jPanel10.add(seleccioneEstacionLabel2, gridBagConstraints);

        tarjetaCylRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tarjetaCylRadioButton.setText("Tarjeta Usuario TCyL");
        tarjetaCylRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarjetaCylRadioButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 220, 12, 0);
        jPanel10.add(tarjetaCylRadioButton, gridBagConstraints);

        tarjetaCreditoRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tarjetaCreditoRadioButton.setSelected(true);
        tarjetaCreditoRadioButton.setText("Tarjeta de crédito");
        tarjetaCreditoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarjetaCreditoRadioButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 220, 0, 0);
        jPanel10.add(tarjetaCreditoRadioButton, gridBagConstraints);

        paso3Panel.add(jPanel10);

        opcionesPanel.setLayout(new java.awt.CardLayout());

        tarjetaCreditoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visa.png"))); // NOI18N
        tarjetaCreditoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarjetaCreditoButtonActionPerformed(evt);
            }
        });

        seleccioneEstacionLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        seleccioneEstacionLabel3.setText("PIN:");

        pinTarjetaField.setToolTipText("Introduce el PIN...");

        aceptarButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        aceptarButton.setText("Aceptar");
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pinTarjetaCreditoPanelLayout = new javax.swing.GroupLayout(pinTarjetaCreditoPanel);
        pinTarjetaCreditoPanel.setLayout(pinTarjetaCreditoPanelLayout);
        pinTarjetaCreditoPanelLayout.setHorizontalGroup(
            pinTarjetaCreditoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pinTarjetaCreditoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(seleccioneEstacionLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pinTarjetaField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(aceptarButton)
                .addContainerGap())
        );
        pinTarjetaCreditoPanelLayout.setVerticalGroup(
            pinTarjetaCreditoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pinTarjetaCreditoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pinTarjetaCreditoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pinTarjetaField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aceptarButton)
                    .addComponent(seleccioneEstacionLabel3))
                .addContainerGap())
        );

        erroresLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        erroresLabel3.setText("Mantenga usted la tarjeta 2 segundos");
        erroresLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout tarjetaCreditoPanelLayout = new javax.swing.GroupLayout(tarjetaCreditoPanel);
        tarjetaCreditoPanel.setLayout(tarjetaCreditoPanelLayout);
        tarjetaCreditoPanelLayout.setHorizontalGroup(
            tarjetaCreditoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tarjetaCreditoPanelLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(tarjetaCreditoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pinTarjetaCreditoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tarjetaCreditoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(erroresLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        tarjetaCreditoPanelLayout.setVerticalGroup(
            tarjetaCreditoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tarjetaCreditoPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tarjetaCreditoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(erroresLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(pinTarjetaCreditoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        opcionesPanel.add(tarjetaCreditoPanel, "card2");

        tarjetaCylButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visa.png"))); // NOI18N
        tarjetaCylButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarjetaCylButtonActionPerformed(evt);
            }
        });

        erroresLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        erroresLabel4.setText("Mantenga usted la tarjeta 2 segundos");
        erroresLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout tarjetaCylPanelLayout = new javax.swing.GroupLayout(tarjetaCylPanel);
        tarjetaCylPanel.setLayout(tarjetaCylPanelLayout);
        tarjetaCylPanelLayout.setHorizontalGroup(
            tarjetaCylPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tarjetaCylPanelLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(erroresLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(114, 114, 114))
            .addGroup(tarjetaCylPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tarjetaCylPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(tarjetaCylButton, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        tarjetaCylPanelLayout.setVerticalGroup(
            tarjetaCylPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tarjetaCylPanelLayout.createSequentialGroup()
                .addContainerGap(289, Short.MAX_VALUE)
                .addComponent(erroresLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(tarjetaCylPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tarjetaCylPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(tarjetaCylButton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        opcionesPanel.add(tarjetaCylPanel, "card2");

        paso3Panel.add(opcionesPanel);

        jPanel11.setLayout(new java.awt.GridBagLayout());

        volver3Button.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        volver3Button.setText("Volver");
        volver3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver3ButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 40, 8, 491);
        jPanel11.add(volver3Button, gridBagConstraints);

        paso3Panel.add(jPanel11);

        getContentPane().add(paso3Panel, "card4");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continuarPaso1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarPaso1ButtonActionPerformed
        controlador.continuarPaso1();
    }//GEN-LAST:event_continuarPaso1ButtonActionPerformed

    private void estacionOrigenSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estacionOrigenSelectorActionPerformed
        actualizarSeleccionEstacionDestino();
    }//GEN-LAST:event_estacionOrigenSelectorActionPerformed

    private void volver3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver3ButtonActionPerformed
        controlador.volverPaso3();
    }//GEN-LAST:event_volver3ButtonActionPerformed

    private void continuarPaso2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarPaso2ButtonActionPerformed
        controlador.continuarPaso2();
    }//GEN-LAST:event_continuarPaso2ButtonActionPerformed

    private void tarjetaCreditoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarjetaCreditoRadioButtonActionPerformed
        desactivarSelectoresTarjeta();
        tarjetaCreditoRadioButton.setSelected(true);
        desactivarPanelesTarjeta();
        tarjetaCreditoPanel.setVisible(true);
    }//GEN-LAST:event_tarjetaCreditoRadioButtonActionPerformed

    private void volver2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver2ButtonActionPerformed
        controlador.volverPaso2();
    }//GEN-LAST:event_volver2ButtonActionPerformed

    private void cambiarTemaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarTemaButtonActionPerformed
        try {
            if (darkTheme) {
                FlatAtomOneLightIJTheme.setup();
                cambiarTemaButton.setText("Tema Oscuro");
            } else {
                FlatAtomOneDarkIJTheme.setup();
                cambiarTemaButton.setText("Tema Claro");
            }
            SwingUtilities.updateComponentTreeUI(this);
            this.pack();
            darkTheme = !darkTheme;
            styleButtons();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_cambiarTemaButtonActionPerformed

    private void bicicletaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bicicletaCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bicicletaCheckBoxActionPerformed

    private void mascotaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mascotaCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mascotaCheckBoxActionPerformed

    private void tarjetaCylRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarjetaCylRadioButtonActionPerformed
        desactivarSelectoresTarjeta();
        tarjetaCylRadioButton.setSelected(true);
        desactivarPanelesTarjeta();
        tarjetaCylPanel.setVisible(true);
    }//GEN-LAST:event_tarjetaCylRadioButtonActionPerformed

    private void intercambiarEstacionesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intercambiarEstacionesButtonActionPerformed
        String origen = (String) estacionOrigenSelector.getSelectedItem();
        String destino = (String) estacionDestinoSelector.getSelectedItem();
        estacionOrigenSelector.setSelectedItem(destino);
        estacionDestinoSelector.setSelectedItem(origen);
    }//GEN-LAST:event_intercambiarEstacionesButtonActionPerformed

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed
        controlador.aceptarPagoTarjetaCredito();
    }//GEN-LAST:event_aceptarButtonActionPerformed

    private void comprarOtroBilleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarOtroBilleteActionPerformed
        limpiar();
        activarPaso(1);
    }//GEN-LAST:event_comprarOtroBilleteActionPerformed

    private void tarjetaCreditoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarjetaCreditoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarjetaCreditoButtonActionPerformed

    private void tarjetaCylButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarjetaCylButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarjetaCylButtonActionPerformed

    private void estacionOrigenSelectorPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_estacionOrigenSelectorPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_estacionOrigenSelectorPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            //UIManager.setLookAndFeel(new FlatIntelliJLaf()); //La mejor interfaz
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JCheckBox bicicletaCheckBox;
    private javax.swing.JButton cambiarTemaButton;
    private javax.swing.JButton comprarOtroBillete;
    private javax.swing.JButton continuarPaso1Button;
    private javax.swing.JButton continuarPaso2Button;
    private javax.swing.JEditorPane dinoPanel;
    private org.jdesktop.swingx.JXLabel erroresLabel2;
    private org.jdesktop.swingx.JXLabel erroresLabel3;
    private org.jdesktop.swingx.JXLabel erroresLabel4;
    private javax.swing.JComboBox<String> estacionDestinoSelector;
    private javax.swing.JComboBox<String> estacionOrigenSelector;
    private org.jdesktop.swingx.JXDatePicker fechaDatePicker;
    private javax.swing.JButton intercambiarEstacionesButton;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox mascotaCheckBox;
    private javax.swing.JPanel opcionesPanel;
    private javax.swing.JLabel paso1Label;
    private javax.swing.JLabel paso1Label1;
    private javax.swing.JLabel paso1Label2;
    private javax.swing.JLabel paso1Label3;
    private javax.swing.JPanel paso1Panel;
    private javax.swing.JPanel paso2Panel;
    private javax.swing.JPanel paso3Panel;
    private javax.swing.JPanel paso4Panel;
    private javax.swing.JPanel pinTarjetaCreditoPanel;
    private javax.swing.JPasswordField pinTarjetaField;
    private org.jdesktop.swingx.JXList rutasList;
    private javax.swing.JLabel seleccioneEstacionLabel;
    private javax.swing.JLabel seleccioneEstacionLabel1;
    private javax.swing.JLabel seleccioneEstacionLabel2;
    private javax.swing.JLabel seleccioneEstacionLabel3;
    private org.jdesktop.swingx.JXButton tarjetaCreditoButton;
    private javax.swing.JPanel tarjetaCreditoPanel;
    private javax.swing.JRadioButton tarjetaCreditoRadioButton;
    private org.jdesktop.swingx.JXButton tarjetaCylButton;
    private javax.swing.JPanel tarjetaCylPanel;
    private javax.swing.JRadioButton tarjetaCylRadioButton;
    private javax.swing.JButton volver2Button;
    private javax.swing.JButton volver3Button;
    // End of variables declaration//GEN-END:variables

    public void activarPaso(int i) {
        desactivarPasos();
        switch (i) {
            case 1:
                paso1Panel.setVisible(true);
                break;
            case 2:
                paso2Panel.setVisible(true);
                break;
            case 3:
                paso3Panel.setVisible(true);
                break;
            case 4:
                paso4Panel.setVisible(true);
                break;
        }
    }

    public void escribirError(int paso) {
        switch (paso) {
            case 1:
                paso1Panel.setVisible(true);
                break;
            case 2:
                paso2Panel.setVisible(true);
                break;
            case 3:
                paso3Panel.setVisible(true);
                break;
        }
    }

    private void desactivarPasos() {
        paso1Panel.setVisible(false);
        paso2Panel.setVisible(false);
        paso3Panel.setVisible(false);
        paso4Panel.setVisible(false);
    }

    public void inicializarEstaciones(ArrayList<String> estaciones) {
        estacionOrigenSelector.removeAllItems();
        for (String estacion : estaciones) {
            estacionOrigenSelector.addItem(estacion);
        }

        Viaje v = controlador.getRandomViaje();
        estacionOrigenSelector.setSelectedItem(v.getEstacionOrigen());
        actualizarSeleccionEstacionDestino();
        estacionOrigenSelector.setSelectedItem(v.getEstacionDestino());
    }

    public void actualizarViajes(ArrayList<Viaje> viajes) {
        viajesListModel.removeAllElements();
        for (Viaje viaje : viajes) {
            viajesListModel.addElement(viaje);
        }
    }
    
    /**
     * Obtiene la fecha actual
     * @return devuelve la fecha actual
     */
    public LocalDateTime getFecha() {
        return fechaDatePicker.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime();
    }
    
    
    public Viaje getSelectedViaje() {
        return (Viaje) rutasList.getSelectedValue();
    }

    public boolean getBicicletaSelection() {
        return bicicletaCheckBox.isSelected();
    }

    public boolean getMascotaSelection() {
        return mascotaCheckBox.isSelected();
    }

    public String getEstacionOrigen() {
        return (String) estacionOrigenSelector.getSelectedItem();
    }

    public String getEstacionDestino() {
        return (String) estacionDestinoSelector.getSelectedItem();
    }

    private void desactivarSelectoresTarjeta() {
        tarjetaCreditoRadioButton.setSelected(false);
        tarjetaCylRadioButton.setSelected(false);
    }

    private void desactivarPanelesTarjeta() {
        tarjetaCylPanel.setVisible(false);
        tarjetaCreditoPanel.setVisible(false);
    }

    public String getPinTarjeta() {
        return pinTarjetaField.getText();
    }

    public void activarPinTarjeta() {
        pinTarjetaCreditoPanel.setVisible(true);
    }

    public void desactivarPinTarjeta() {
        pinTarjetaCreditoPanel.setVisible(false);
    }

    public void mensajePaso3(String mensaje, Utiles.codigoMensaje codigoMensaje) {
        erroresLabel3.setText(mensaje);
        switch (codigoMensaje) {
            case ERROR:
                erroresLabel3.setForeground(Color.red);
                break;
            case NORMAL:
                erroresLabel3.setForeground(Color.black);
                break;
        }
    }

    private void limpiar() { //A BARRER!!!!
        mensajePaso3("Mantenga usted la tarjeta 2 segundos", Utiles.codigoMensaje.NORMAL);
        bicicletaCheckBox.setSelected(false);
        mascotaCheckBox.setSelected(false);
        tarjetaCylPanel.setVisible(false);
        tarjetaCreditoPanel.setVisible(true);
        fechaDatePicker.setDate(new Date());
        inicializarEstaciones(controlador.getEstaciones());
    }

    private void actualizarSeleccionEstacionDestino() {
        estacionDestinoSelector.removeAllItems();
        ArrayList<String> estacionesDestinoPosibles = controlador.getPosiblesEstacionesDestino(getEstacionOrigen());
        for (String estacion : estacionesDestinoPosibles) {
            estacionDestinoSelector.addItem(estacion);
        }
    }
}
