/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uva.ipc.vista;

import java.util.*;
import java.text.SimpleDateFormat;
import com.formdev.flatlaf.*;
import java.awt.Dimension;
import java.net.URL;
import java.time.*;
import javax.swing.*;
import uva.ipc.controlador.Controlador;
import uva.ipc.modelo.Viaje;

/**
 *
 * @author danie
 */
public class Vista extends javax.swing.JFrame {

    private Controlador controlador;
    private DefaultListModel<Viaje> viajesListModel = new DefaultListModel<>();

    /**
     * Creates new form MainFrame
     */
    public Vista() {
        initComponents();
        this.controlador = new Controlador(this);
        rutasList.setModel(viajesListModel);
        setMinimumSize(new Dimension(650, 700)); //POR QUE AQUI!!!?!?!?!?! Maldito sea el javaswin
        tarjetaCylPanel.setVisible(false);

        /*JWebBrowser webBrowser = new JWebBrowser();
        webBrowser.navigate("https://dino-url.com");
        dinoPanel.add(webBrowser);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paso1Panel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        paso1Label = new javax.swing.JLabel();
        seleccioneEstacionLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        estacionOrigenSelector = new javax.swing.JComboBox<>();
        estacionDestinoSelector = new javax.swing.JComboBox<>();
        intercambiarEstacionesButton = new javax.swing.JButton();
        fechaDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jPanel5 = new javax.swing.JPanel();
        continuarPaso1Button = new javax.swing.JButton();
        errores1TextField = new javax.swing.JTextField();
        cambiarTemaButton = new javax.swing.JButton();
        paso2Panel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        paso1Label1 = new javax.swing.JLabel();
        seleccioneEstacionLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        rutasList = new org.jdesktop.swingx.JXList();
        jPanel8 = new javax.swing.JPanel();
        bicicletaImagenjLabel = new javax.swing.JLabel();
        mascotajLabel = new javax.swing.JLabel();
        bicicletaCheckBox = new javax.swing.JCheckBox();
        mascotaCheckBox = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        volver2Button = new javax.swing.JButton();
        continuarPaso2Button = new javax.swing.JButton();
        errores2TextField = new javax.swing.JTextField();
        paso4Panel = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        dinoPanel = new javax.swing.JPanel();
        paso1Label3 = new javax.swing.JLabel();
        comprarOtroBillete = new javax.swing.JButton();
        paso3Panel = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        paso1Label2 = new javax.swing.JLabel();
        seleccioneEstacionLabel2 = new javax.swing.JLabel();
        tarjetaCylRadioButton = new javax.swing.JRadioButton();
        tarjetaCreditoRadioButton = new javax.swing.JRadioButton();
        opcionesPanel = new javax.swing.JPanel();
        tarjetaCreditoPanel = new javax.swing.JPanel();
        errores3TextField = new javax.swing.JTextField();
        aceptarButton = new javax.swing.JButton();
        pinTarjetaField = new javax.swing.JPasswordField();
        seleccioneEstacionLabel3 = new javax.swing.JLabel();
        jXButton1 = new org.jdesktop.swingx.JXButton();
        tarjetaCylPanel = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        volver3Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tren Castilla y León");
        getContentPane().setLayout(new java.awt.CardLayout());

        paso1Panel.setEnabled(false);
        paso1Panel.setMaximumSize(new java.awt.Dimension(700, 700));
        paso1Panel.setMinimumSize(new java.awt.Dimension(600, 600));
        paso1Panel.setPreferredSize(new java.awt.Dimension(600, 600));
        paso1Panel.setLayout(new javax.swing.BoxLayout(paso1Panel, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        paso1Label.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        paso1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paso1Label.setText("Paso 1");

        seleccioneEstacionLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        seleccioneEstacionLabel.setText("Seleccione las estaciones");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(paso1Label))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(seleccioneEstacionLabel)))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(paso1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seleccioneEstacionLabel)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        paso1Panel.add(jPanel2);

        estacionOrigenSelector.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        estacionOrigenSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estacionOrigenSelectorActionPerformed(evt);
            }
        });

        estacionDestinoSelector.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        intercambiarEstacionesButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        intercambiarEstacionesButton.setText("Intercambiar Estaciones");
        intercambiarEstacionesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intercambiarEstacionesButtonActionPerformed(evt);
            }
        });

        fechaDatePicker.setDate(new java.util.Date());
        fechaDatePicker.setDoubleBuffered(true);
        fechaDatePicker.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estacionDestinoSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estacionOrigenSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(intercambiarEstacionesButton)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(estacionOrigenSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(estacionDestinoSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(intercambiarEstacionesButton)))
                .addGap(70, 70, 70)
                .addComponent(fechaDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        fechaDatePicker.setFormats(new SimpleDateFormat("dd/MM/yyyy"));
        fechaDatePicker.getMonthView().setFirstDayOfWeek(Calendar.MONDAY);
        fechaDatePicker.getMonthView().setLowerBound(new Date());

        paso1Panel.add(jPanel3);

        continuarPaso1Button.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        continuarPaso1Button.setText("Continuar");
        continuarPaso1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarPaso1ButtonActionPerformed(evt);
            }
        });

        errores1TextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        errores1TextField.setText("Comprobacion Errores");

        cambiarTemaButton.setText("Tema Oscuro");
        cambiarTemaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarTemaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(cambiarTemaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 369, Short.MAX_VALUE)
                .addComponent(continuarPaso1Button)
                .addGap(22, 22, 22))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(errores1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(errores1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(continuarPaso1Button)
                    .addComponent(cambiarTemaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        paso1Panel.add(jPanel5);

        getContentPane().add(paso1Panel, "card2");

        paso2Panel.setEnabled(false);
        paso2Panel.setMaximumSize(new java.awt.Dimension(700, 700));
        paso2Panel.setMinimumSize(new java.awt.Dimension(600, 600));
        paso2Panel.setPreferredSize(new java.awt.Dimension(600, 600));
        paso2Panel.setLayout(new java.awt.GridLayout(4, 1));

        paso1Label1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        paso1Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paso1Label1.setText("Paso 2");

        seleccioneEstacionLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        seleccioneEstacionLabel1.setText("Selecciona tu tren");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paso1Label1)
                    .addComponent(seleccioneEstacionLabel1))
                .addContainerGap(241, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(paso1Label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seleccioneEstacionLabel1)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        paso2Panel.add(jPanel6);

        DefaultListModel<String> listModel = new DefaultListModel<>();
        rutasList.setModel(listModel);
        jScrollPane2.setViewportView(rutasList);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        paso2Panel.add(jPanel7);

        bicicletaImagenjLabel.setText("bicicletaImagen");

        mascotajLabel.setText("mascotaImagen");

        bicicletaCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bicicletaCheckBox.setText("Bicicleta");
        bicicletaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bicicletaCheckBoxActionPerformed(evt);
            }
        });

        mascotaCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mascotaCheckBox.setText("Mascota");
        mascotaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mascotaCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bicicletaCheckBox)
                    .addComponent(mascotaCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mascotajLabel)
                    .addComponent(bicicletaImagenjLabel))
                .addContainerGap(333, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bicicletaImagenjLabel)
                    .addComponent(bicicletaCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mascotaCheckBox)
                    .addComponent(mascotajLabel))
                .addGap(34, 34, 34))
        );

        paso2Panel.add(jPanel8);

        volver2Button.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        volver2Button.setText("Volver");
        volver2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver2ButtonActionPerformed(evt);
            }
        });

        continuarPaso2Button.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        continuarPaso2Button.setText("Continuar");
        continuarPaso2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarPaso2ButtonActionPerformed(evt);
            }
        });

        errores2TextField.setText("Comprobacion Errores");
        errores2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errores2TextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(volver2Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 370, Short.MAX_VALUE)
                .addComponent(continuarPaso2Button)
                .addGap(30, 30, 30))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(errores2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(errores2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volver2Button)
                    .addComponent(continuarPaso2Button))
                .addGap(31, 31, 31))
        );

        paso2Panel.add(jPanel9);

        getContentPane().add(paso2Panel, "card3");

        paso4Panel.setEnabled(false);
        paso4Panel.setMaximumSize(new java.awt.Dimension(700, 700));
        paso4Panel.setMinimumSize(new java.awt.Dimension(600, 600));
        paso4Panel.setPreferredSize(new java.awt.Dimension(600, 600));
        paso4Panel.setLayout(new javax.swing.BoxLayout(paso4Panel, javax.swing.BoxLayout.PAGE_AXIS));

        dinoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout dinoPanelLayout = new javax.swing.GroupLayout(dinoPanel);
        dinoPanel.setLayout(dinoPanelLayout);
        dinoPanelLayout.setHorizontalGroup(
            dinoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );
        dinoPanelLayout.setVerticalGroup(
            dinoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        paso1Label3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        paso1Label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paso1Label3.setText("Pago confirmado");

        comprarOtroBillete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comprarOtroBillete.setText("Comprar otro billete");
        comprarOtroBillete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarOtroBilleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(paso1Label3))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(comprarOtroBillete, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(dinoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(paso1Label3)
                .addGap(37, 37, 37)
                .addComponent(comprarOtroBillete, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(dinoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        paso4Panel.add(jPanel12);

        getContentPane().add(paso4Panel, "card4");

        paso3Panel.setEnabled(false);
        paso3Panel.setMaximumSize(new java.awt.Dimension(700, 700));
        paso3Panel.setMinimumSize(new java.awt.Dimension(600, 600));
        paso3Panel.setPreferredSize(new java.awt.Dimension(600, 600));
        paso3Panel.setLayout(new javax.swing.BoxLayout(paso3Panel, javax.swing.BoxLayout.PAGE_AXIS));

        paso1Label2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        paso1Label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paso1Label2.setText("Paso 3");

        seleccioneEstacionLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        seleccioneEstacionLabel2.setText("Selecciona el método de pago");

        tarjetaCylRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tarjetaCylRadioButton.setText("Tarjeta Usuario TCyL");
        tarjetaCylRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarjetaCylRadioButtonActionPerformed(evt);
            }
        });

        tarjetaCreditoRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tarjetaCreditoRadioButton.setSelected(true);
        tarjetaCreditoRadioButton.setText("Tarjeta de crédito");
        tarjetaCreditoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarjetaCreditoRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seleccioneEstacionLabel2)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(paso1Label2))))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tarjetaCylRadioButton)
                            .addComponent(tarjetaCreditoRadioButton))))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(paso1Label2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seleccioneEstacionLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tarjetaCreditoRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tarjetaCylRadioButton)
                .addContainerGap())
        );

        paso3Panel.add(jPanel10);

        opcionesPanel.setLayout(new java.awt.CardLayout());

        errores3TextField.setText("Comprobacion Errores");
        errores3TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errores3TextFieldActionPerformed(evt);
            }
        });

        aceptarButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        aceptarButton.setText("Aceptar");
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });

        pinTarjetaField.setToolTipText("Introduce el PIN...");

        seleccioneEstacionLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        seleccioneEstacionLabel3.setText("PIN:");

        jXButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tarjetaCreditoPanelLayout = new javax.swing.GroupLayout(tarjetaCreditoPanel);
        tarjetaCreditoPanel.setLayout(tarjetaCreditoPanelLayout);
        tarjetaCreditoPanelLayout.setHorizontalGroup(
            tarjetaCreditoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tarjetaCreditoPanelLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(tarjetaCreditoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jXButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tarjetaCreditoPanelLayout.createSequentialGroup()
                        .addComponent(seleccioneEstacionLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tarjetaCreditoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errores3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tarjetaCreditoPanelLayout.createSequentialGroup()
                                .addComponent(pinTarjetaField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(aceptarButton)))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        tarjetaCreditoPanelLayout.setVerticalGroup(
            tarjetaCreditoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tarjetaCreditoPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jXButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(errores3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(tarjetaCreditoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pinTarjetaField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seleccioneEstacionLabel3)
                    .addComponent(aceptarButton))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        opcionesPanel.add(tarjetaCreditoPanel, "card2");

        javax.swing.GroupLayout tarjetaCylPanelLayout = new javax.swing.GroupLayout(tarjetaCylPanel);
        tarjetaCylPanel.setLayout(tarjetaCylPanelLayout);
        tarjetaCylPanelLayout.setHorizontalGroup(
            tarjetaCylPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        tarjetaCylPanelLayout.setVerticalGroup(
            tarjetaCylPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );

        opcionesPanel.add(tarjetaCylPanel, "card2");

        paso3Panel.add(opcionesPanel);

        volver3Button.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        volver3Button.setText("Volver");
        volver3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver3ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(volver3Button)
                .addContainerGap(491, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(volver3Button)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        paso3Panel.add(jPanel11);

        getContentPane().add(paso3Panel, "card4");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continuarPaso1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarPaso1ButtonActionPerformed
        controlador.continuarPaso1();
        System.out.println(getClass().getResource("/Visa.png"));
    }//GEN-LAST:event_continuarPaso1ButtonActionPerformed

    private void estacionOrigenSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estacionOrigenSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estacionOrigenSelectorActionPerformed

    private void volver3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver3ButtonActionPerformed
        controlador.volverPaso3();
    }//GEN-LAST:event_volver3ButtonActionPerformed

    private void continuarPaso2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarPaso2ButtonActionPerformed
        controlador.continuarPaso2();
    }//GEN-LAST:event_continuarPaso2ButtonActionPerformed

    private void tarjetaCreditoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarjetaCreditoRadioButtonActionPerformed
        desactivarSelectoresTarjeta();
        tarjetaCreditoRadioButton.setSelected(true);
        desactivarPanelesTarjeta();
        tarjetaCreditoPanel.setVisible(true);
    }//GEN-LAST:event_tarjetaCreditoRadioButtonActionPerformed

    private void errores2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errores2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_errores2TextFieldActionPerformed

    private void errores3TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errores3TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_errores3TextFieldActionPerformed

    private void volver2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver2ButtonActionPerformed
        controlador.volverPaso2();
    }//GEN-LAST:event_volver2ButtonActionPerformed

    private void cambiarTemaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarTemaButtonActionPerformed
        try {
            if (UIManager.getLookAndFeel() instanceof FlatIntelliJLaf) {
                UIManager.setLookAndFeel(new FlatDarkLaf());
            } else {
                UIManager.setLookAndFeel(new FlatIntelliJLaf());
            }
            SwingUtilities.updateComponentTreeUI(JFrame.getWindows()[0]);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_cambiarTemaButtonActionPerformed

    private void bicicletaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bicicletaCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bicicletaCheckBoxActionPerformed

    private void mascotaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mascotaCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mascotaCheckBoxActionPerformed

    private void tarjetaCylRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarjetaCylRadioButtonActionPerformed
        desactivarSelectoresTarjeta();
        tarjetaCylRadioButton.setSelected(true);
        desactivarPanelesTarjeta();
        tarjetaCylPanel.setVisible(true);
    }//GEN-LAST:event_tarjetaCylRadioButtonActionPerformed

    private void intercambiarEstacionesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intercambiarEstacionesButtonActionPerformed
        int index = estacionDestinoSelector.getSelectedIndex();
        estacionDestinoSelector.setSelectedIndex(estacionOrigenSelector.getSelectedIndex());
        estacionOrigenSelector.setSelectedIndex(index);
    }//GEN-LAST:event_intercambiarEstacionesButtonActionPerformed

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed
        controlador.aceptarPagoTarjetaCredito();
    }//GEN-LAST:event_aceptarButtonActionPerformed

    private void comprarOtroBilleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarOtroBilleteActionPerformed
        activarPaso(1);
    }//GEN-LAST:event_comprarOtroBilleteActionPerformed

    private void jXButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jXButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JCheckBox bicicletaCheckBox;
    private javax.swing.JLabel bicicletaImagenjLabel;
    private javax.swing.JButton cambiarTemaButton;
    private javax.swing.JButton comprarOtroBillete;
    private javax.swing.JButton continuarPaso1Button;
    private javax.swing.JButton continuarPaso2Button;
    private javax.swing.JPanel dinoPanel;
    private javax.swing.JTextField errores1TextField;
    private javax.swing.JTextField errores2TextField;
    private javax.swing.JTextField errores3TextField;
    private javax.swing.JComboBox<String> estacionDestinoSelector;
    private javax.swing.JComboBox<String> estacionOrigenSelector;
    private org.jdesktop.swingx.JXDatePicker fechaDatePicker;
    private javax.swing.JButton intercambiarEstacionesButton;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXButton jXButton1;
    private javax.swing.JCheckBox mascotaCheckBox;
    private javax.swing.JLabel mascotajLabel;
    private javax.swing.JPanel opcionesPanel;
    private javax.swing.JLabel paso1Label;
    private javax.swing.JLabel paso1Label1;
    private javax.swing.JLabel paso1Label2;
    private javax.swing.JLabel paso1Label3;
    private javax.swing.JPanel paso1Panel;
    private javax.swing.JPanel paso2Panel;
    private javax.swing.JPanel paso3Panel;
    private javax.swing.JPanel paso4Panel;
    private javax.swing.JPasswordField pinTarjetaField;
    private org.jdesktop.swingx.JXList rutasList;
    private javax.swing.JLabel seleccioneEstacionLabel;
    private javax.swing.JLabel seleccioneEstacionLabel1;
    private javax.swing.JLabel seleccioneEstacionLabel2;
    private javax.swing.JLabel seleccioneEstacionLabel3;
    private javax.swing.JPanel tarjetaCreditoPanel;
    private javax.swing.JRadioButton tarjetaCreditoRadioButton;
    private javax.swing.JPanel tarjetaCylPanel;
    private javax.swing.JRadioButton tarjetaCylRadioButton;
    private javax.swing.JButton volver2Button;
    private javax.swing.JButton volver3Button;
    // End of variables declaration//GEN-END:variables

    public void activarPaso(int i) {
        desactivarPasos();
        switch (i) {
            case 1:
                paso1Panel.setVisible(true);
                break;
            case 2:
                paso2Panel.setVisible(true);
                break;
            case 3:
                paso3Panel.setVisible(true);
                break;
            case 4:
                paso4Panel.setVisible(true);
                break;
        }
    }

    public void escribirError(int paso) {
        switch (paso) {
            case 1:
                paso1Panel.setVisible(true);
                break;
            case 2:
                paso2Panel.setVisible(true);
                break;
            case 3:
                paso3Panel.setVisible(true);
                break;
        }
    }

    private void desactivarPasos() {
        paso1Panel.setVisible(false);
        paso2Panel.setVisible(false);
        paso3Panel.setVisible(false);
        paso4Panel.setVisible(false);
    }

    public void inicializarEstaciones(ArrayList<String> estaciones) {
        for (String estacion : estaciones) {
            estacionOrigenSelector.addItem(estacion);
            estacionDestinoSelector.addItem(estacion);
        }
        estacionDestinoSelector.setSelectedIndex(estacionDestinoSelector.getItemCount() - 1);
    }

    public void actualizarViajes(ArrayList<Viaje> viajes) {
        viajesListModel.removeAllElements();
        for (Viaje viaje : viajes) {
            viajesListModel.addElement(viaje);
        }
    }

    public LocalDateTime getFecha() {
        return fechaDatePicker.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime();
    }

    public Viaje getSelectedViaje() {
        return (Viaje) rutasList.getSelectedValue();
    }

    public boolean getBicicletaSelection() {
        return bicicletaCheckBox.isSelected();
    }

    public boolean getMascotaSelection() {
        return mascotaCheckBox.isSelected();
    }

    public String getEstacionOrigen() {
        return (String) estacionOrigenSelector.getSelectedItem();
    }

    public String getEstacionDestino() {
        return (String) estacionDestinoSelector.getSelectedItem();
    }

    private void desactivarSelectoresTarjeta() {
        tarjetaCreditoRadioButton.setSelected(false);
        tarjetaCylRadioButton.setSelected(false);
    }

    private void desactivarPanelesTarjeta() {
        tarjetaCylPanel.setVisible(false);
        tarjetaCreditoPanel.setVisible(false);
    }

    public String getPinTarjeta() {
        return pinTarjetaField.getText();
    }
}
