/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uva.ipc.vista;

import java.util.*;
import java.text.SimpleDateFormat;
import com.formdev.flatlaf.*;
import java.time.*;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import uva.ipc.controlador.Controlador;
import uva.ipc.modelo.Viaje;

/**
 *
 * @author danie
 */
public class Vista extends javax.swing.JFrame {

    private Controlador controlador;
    private DefaultListModel<Viaje> viajesListModel = new DefaultListModel<>();

    /**
     * Creates new form MainFrame
     */
    public Vista() {
        initComponents();
        this.controlador = new Controlador(this);
        rutasList.setModel(viajesListModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paso1Panel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        paso1Label = new javax.swing.JLabel();
        seleccioneEstacionLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        estacionOrigenSelector = new javax.swing.JComboBox<>();
        estacionDestinoSelector = new javax.swing.JComboBox<>();
        intercambiarEstacionesButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        fechaDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jPanel5 = new javax.swing.JPanel();
        continuarPaso1Button = new javax.swing.JButton();
        errores1TextField = new javax.swing.JTextField();
        cambiarTemaButton = new javax.swing.JButton();
        paso2Panel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        paso1Label1 = new javax.swing.JLabel();
        seleccioneEstacionLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        rutasList = new org.jdesktop.swingx.JXList();
        jPanel8 = new javax.swing.JPanel();
        bicicletaImagenjLabel = new javax.swing.JLabel();
        mascotajLabel = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        volver2Button = new javax.swing.JButton();
        continuarPaso2Button = new javax.swing.JButton();
        errores2TextField = new javax.swing.JTextField();
        paso3Panel = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        paso1Label2 = new javax.swing.JLabel();
        seleccioneEstacionLabel2 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        RadioButton = new javax.swing.JRadioButton();
        volver3Button = new javax.swing.JButton();
        errores3TextField = new javax.swing.JTextField();
        RadioButton1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tren Castilla y León");
        getContentPane().setLayout(new java.awt.CardLayout());

        paso1Panel.setEnabled(false);
        paso1Panel.setMaximumSize(new java.awt.Dimension(700, 700));
        paso1Panel.setMinimumSize(new java.awt.Dimension(600, 600));
        paso1Panel.setPreferredSize(new java.awt.Dimension(600, 600));
        paso1Panel.setLayout(new java.awt.GridLayout(4, 1));

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        paso1Label.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        paso1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paso1Label.setText("Paso 1");

        seleccioneEstacionLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        seleccioneEstacionLabel.setText("Seleccione las estaciones");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(paso1Label))
                    .addComponent(seleccioneEstacionLabel))
                .addContainerGap(227, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(paso1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seleccioneEstacionLabel)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        paso1Panel.add(jPanel2);

        estacionOrigenSelector.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        estacionOrigenSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estacionOrigenSelectorActionPerformed(evt);
            }
        });

        estacionDestinoSelector.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        intercambiarEstacionesButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        intercambiarEstacionesButton.setText("Intercambiar Estaciones");
        intercambiarEstacionesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intercambiarEstacionesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(estacionDestinoSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estacionOrigenSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(intercambiarEstacionesButton)
                .addContainerGap(287, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(intercambiarEstacionesButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(estacionOrigenSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(estacionDestinoSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        paso1Panel.add(jPanel3);

        fechaDatePicker.setDate(new java.util.Date());
        fechaDatePicker.setDoubleBuffered(true);
        fechaDatePicker.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(fechaDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(272, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(fechaDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        fechaDatePicker.setFormats(new SimpleDateFormat("dd/MM/yyyy"));
        fechaDatePicker.getMonthView().setFirstDayOfWeek(Calendar.MONDAY);

        paso1Panel.add(jPanel4);

        continuarPaso1Button.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        continuarPaso1Button.setText("Continuar");
        continuarPaso1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarPaso1ButtonActionPerformed(evt);
            }
        });

        errores1TextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        errores1TextField.setText("Comprobacion Errores");

        cambiarTemaButton.setText("Tema Oscuro");
        cambiarTemaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarTemaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(errores1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(cambiarTemaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(continuarPaso1Button)
                .addGap(22, 22, 22))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(errores1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(continuarPaso1Button)
                    .addComponent(cambiarTemaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        paso1Panel.add(jPanel5);

        getContentPane().add(paso1Panel, "card2");

        paso2Panel.setEnabled(false);
        paso2Panel.setMaximumSize(new java.awt.Dimension(700, 700));
        paso2Panel.setMinimumSize(new java.awt.Dimension(600, 600));
        paso2Panel.setPreferredSize(new java.awt.Dimension(600, 600));
        paso2Panel.setLayout(new java.awt.GridLayout(4, 1));

        paso1Label1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        paso1Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paso1Label1.setText("Paso 2");

        seleccioneEstacionLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        seleccioneEstacionLabel1.setText("Selecciona tu tren");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paso1Label1)
                    .addComponent(seleccioneEstacionLabel1))
                .addContainerGap(241, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(paso1Label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seleccioneEstacionLabel1)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        paso2Panel.add(jPanel6);

        DefaultListModel<String> listModel = new DefaultListModel<>();
        rutasList.setModel(listModel);
        jScrollPane2.setViewportView(rutasList);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paso2Panel.add(jPanel7);

        bicicletaImagenjLabel.setText("bicicletaImagen");

        mascotajLabel.setText("mascotaImagen");

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBox1.setText("Bicicleta");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBox2.setText("Mascota");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mascotajLabel)
                    .addComponent(bicicletaImagenjLabel))
                .addContainerGap(333, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bicicletaImagenjLabel)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox2)
                    .addComponent(mascotajLabel))
                .addGap(34, 34, 34))
        );

        paso2Panel.add(jPanel8);

        volver2Button.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        volver2Button.setText("Volver");
        volver2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver2ButtonActionPerformed(evt);
            }
        });

        continuarPaso2Button.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        continuarPaso2Button.setText("Continuar");
        continuarPaso2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarPaso2ButtonActionPerformed(evt);
            }
        });

        errores2TextField.setText("Comprobacion Errores");
        errores2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errores2TextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(volver2Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 370, Short.MAX_VALUE)
                .addComponent(continuarPaso2Button)
                .addGap(30, 30, 30))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(errores2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(errores2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volver2Button)
                    .addComponent(continuarPaso2Button))
                .addGap(31, 31, 31))
        );

        paso2Panel.add(jPanel9);

        getContentPane().add(paso2Panel, "card3");

        paso3Panel.setEnabled(false);
        paso3Panel.setMaximumSize(new java.awt.Dimension(700, 700));
        paso3Panel.setMinimumSize(new java.awt.Dimension(600, 600));
        paso3Panel.setPreferredSize(new java.awt.Dimension(600, 600));
        paso3Panel.setLayout(new java.awt.GridLayout(2, 1));

        paso1Label2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        paso1Label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paso1Label2.setText("Paso 3");

        seleccioneEstacionLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        seleccioneEstacionLabel2.setText("Selecciona el método de pago");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seleccioneEstacionLabel2)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(paso1Label2)))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(paso1Label2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seleccioneEstacionLabel2)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        paso3Panel.add(jPanel10);

        RadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RadioButton.setText("Tarjeta de crédito");
        RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonActionPerformed(evt);
            }
        });

        volver3Button.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        volver3Button.setText("Volver");
        volver3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver3ButtonActionPerformed(evt);
            }
        });

        errores3TextField.setText("Comprobacion Errores");
        errores3TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errores3TextFieldActionPerformed(evt);
            }
        });

        RadioButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RadioButton1.setText("Tarjeta Usuario TCyL");
        RadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(errores3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(volver3Button))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadioButton1)
                            .addComponent(RadioButton))))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(RadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadioButton1)
                .addGap(39, 39, 39)
                .addComponent(errores3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(volver3Button)
                .addGap(41, 41, 41))
        );

        paso3Panel.add(jPanel11);

        getContentPane().add(paso3Panel, "card4");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continuarPaso1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarPaso1ButtonActionPerformed
        controlador.continuarPaso1();
    }//GEN-LAST:event_continuarPaso1ButtonActionPerformed

    private void estacionOrigenSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estacionOrigenSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estacionOrigenSelectorActionPerformed

    private void volver3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver3ButtonActionPerformed
        controlador.volverPaso3();
    }//GEN-LAST:event_volver3ButtonActionPerformed

    private void continuarPaso2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarPaso2ButtonActionPerformed
        controlador.continuarPaso2();
    }//GEN-LAST:event_continuarPaso2ButtonActionPerformed

    private void RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonActionPerformed

    private void errores2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errores2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_errores2TextFieldActionPerformed

    private void errores3TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errores3TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_errores3TextFieldActionPerformed

    private void volver2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver2ButtonActionPerformed
        controlador.volverPaso2();
    }//GEN-LAST:event_volver2ButtonActionPerformed

    private void cambiarTemaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarTemaButtonActionPerformed
        try {
            if (UIManager.getLookAndFeel() instanceof FlatIntelliJLaf) {
                UIManager.setLookAndFeel(new FlatDarkLaf());
            } else {
                UIManager.setLookAndFeel(new FlatIntelliJLaf());
            }
            SwingUtilities.updateComponentTreeUI(JFrame.getWindows()[0]);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_cambiarTemaButtonActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void RadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButton1ActionPerformed

    private void intercambiarEstacionesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intercambiarEstacionesButtonActionPerformed
        int index = estacionDestinoSelector.getSelectedIndex();
        estacionDestinoSelector.setSelectedIndex(estacionOrigenSelector.getSelectedIndex());
        estacionOrigenSelector.setSelectedIndex(index);
    }//GEN-LAST:event_intercambiarEstacionesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioButton;
    private javax.swing.JRadioButton RadioButton1;
    private javax.swing.JLabel bicicletaImagenjLabel;
    private javax.swing.JButton cambiarTemaButton;
    private javax.swing.JButton continuarPaso1Button;
    private javax.swing.JButton continuarPaso2Button;
    private javax.swing.JTextField errores1TextField;
    private javax.swing.JTextField errores2TextField;
    private javax.swing.JTextField errores3TextField;
    private javax.swing.JComboBox<String> estacionDestinoSelector;
    private javax.swing.JComboBox<String> estacionOrigenSelector;
    private org.jdesktop.swingx.JXDatePicker fechaDatePicker;
    private javax.swing.JButton intercambiarEstacionesButton;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel mascotajLabel;
    private javax.swing.JLabel paso1Label;
    private javax.swing.JLabel paso1Label1;
    private javax.swing.JLabel paso1Label2;
    private javax.swing.JPanel paso1Panel;
    private javax.swing.JPanel paso2Panel;
    private javax.swing.JPanel paso3Panel;
    private org.jdesktop.swingx.JXList rutasList;
    private javax.swing.JLabel seleccioneEstacionLabel;
    private javax.swing.JLabel seleccioneEstacionLabel1;
    private javax.swing.JLabel seleccioneEstacionLabel2;
    private javax.swing.JButton volver2Button;
    private javax.swing.JButton volver3Button;
    // End of variables declaration//GEN-END:variables

    public void activarPaso(int i) {
        desactivarPasos();
        switch (i) {
            case 1:
                paso1Panel.setVisible(true);
                break;
            case 2:
                paso2Panel.setVisible(true);
                break;
            case 3:
                paso3Panel.setVisible(true);
                break;
        }
    }

    public void escribirError(int paso) {
        switch (paso) {
            case 1:
                paso1Panel.setVisible(true);
                break;
            case 2:
                paso2Panel.setVisible(true);
                break;
            case 3:
                paso3Panel.setVisible(true);
                break;
        }
    }

    private void desactivarPasos() {
        paso1Panel.setVisible(false);
        paso2Panel.setVisible(false);
        paso3Panel.setVisible(false);
    }

    public void inicializarEstaciones(ArrayList<String> estaciones) {
        for (String estacion : estaciones) {
            estacionOrigenSelector.addItem(estacion);
            estacionDestinoSelector.addItem(estacion);
        }
        estacionDestinoSelector.setSelectedIndex(estacionDestinoSelector.getItemCount() - 1);
    }

    public void actualizarViajes(ArrayList<Viaje> viajes) {
        viajesListModel.removeAllElements();
        for (Viaje viaje : viajes) {
            viajesListModel.addElement(viaje);
        }
    }

    public LocalDateTime getFecha() {
        return fechaDatePicker.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime();
    }

    public String getEstacionOrigen() {
        return (String) estacionOrigenSelector.getSelectedItem();
    }

    public String getEstacionDestino() {
        return (String) estacionDestinoSelector.getSelectedItem();
    }
}
