/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uva.ipc.vista;

/**
 *
 * @author danie
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public Vista() {
        initComponents();
        paso3Panel.setVisible(false);
        paso2Panel.setVisible(true);
        paso1Panel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paso1Panel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        paso1Label = new javax.swing.JLabel();
        seleccioneEstacionLabel = new javax.swing.JLabel();
        trenLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bicicletaComboBox = new javax.swing.JComboBox<>();
        mascotaComboBox = new javax.swing.JComboBox<>();
        intercambiarEstacionesButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        fechaSpinner = new javax.swing.JSpinner();
        fechaImagenLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        continuar1Button = new javax.swing.JButton();
        errores1TextField = new javax.swing.JTextField();
        paso2Panel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        paso2Label = new javax.swing.JLabel();
        seleccioneEstacion2Label = new javax.swing.JLabel();
        tren2Label = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaTrenesDisponiblesjTextArea = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        bicicletacheckbox1 = new java.awt.Checkbox();
        mascotacheckbox2 = new java.awt.Checkbox();
        bicicletaImagenjLabel = new javax.swing.JLabel();
        mascotajLabel = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        volver2Button = new javax.swing.JButton();
        continuar2Button = new javax.swing.JButton();
        errores2TextField = new javax.swing.JTextField();
        paso3Panel = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        paso3Label = new javax.swing.JLabel();
        seleccioneEstacion3Label = new javax.swing.JLabel();
        tren3Label = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        RadioButton = new javax.swing.JRadioButton();
        volver3Button = new javax.swing.JButton();
        errores3TextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        paso1Panel.setEnabled(false);
        paso1Panel.setMaximumSize(new java.awt.Dimension(700, 700));
        paso1Panel.setMinimumSize(new java.awt.Dimension(600, 600));
        paso1Panel.setPreferredSize(new java.awt.Dimension(600, 600));
        paso1Panel.setLayout(new java.awt.GridLayout(4, 1));

        paso1Label.setText("Paso 1");

        seleccioneEstacionLabel.setText("Seleccione las estaciones");

        trenLabel.setText("Tren Castilla y León");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seleccioneEstacionLabel)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(paso1Label)
                        .addGap(66, 66, 66)))
                .addContainerGap(285, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(trenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(49, 49, 49))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(trenLabel)
                .addGap(1, 1, 1)
                .addComponent(paso1Label)
                .addGap(31, 31, 31)
                .addComponent(seleccioneEstacionLabel)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        paso1Panel.add(jPanel2);

        bicicletaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        bicicletaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bicicletaComboBoxActionPerformed(evt);
            }
        });

        mascotaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        intercambiarEstacionesButton.setText("Intercambiar Estaciones");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mascotaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bicicletaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                .addComponent(intercambiarEstacionesButton)
                .addGap(36, 36, 36))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(bicicletaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mascotaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(intercambiarEstacionesButton)
                        .addGap(20, 20, 20))))
        );

        paso1Panel.add(jPanel3);

        fechaSpinner.setModel(new javax.swing.SpinnerDateModel());

        fechaImagenLabel.setText("fechaImagen");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(fechaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(fechaImagenLabel)
                .addContainerGap(323, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaImagenLabel))
                .addGap(29, 29, 29))
        );

        paso1Panel.add(jPanel4);

        continuar1Button.setText("Continuar");
        continuar1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuar1ButtonActionPerformed(evt);
            }
        });

        errores1TextField.setText("Comprobacion Errores");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(continuar1Button))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(errores1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(errores1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(continuar1Button)
                .addGap(23, 23, 23))
        );

        paso1Panel.add(jPanel5);

        getContentPane().add(paso1Panel, "card2");

        paso2Panel.setEnabled(false);
        paso2Panel.setMaximumSize(new java.awt.Dimension(700, 700));
        paso2Panel.setMinimumSize(new java.awt.Dimension(600, 600));
        paso2Panel.setPreferredSize(new java.awt.Dimension(600, 600));
        paso2Panel.setLayout(new java.awt.GridLayout(4, 1));

        paso2Label.setText("Paso 2");

        seleccioneEstacion2Label.setText("Seleccione las estaciones");

        tren2Label.setText("Tren Castilla y León");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seleccioneEstacion2Label)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(paso2Label)
                                .addGap(66, 66, 66))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tren2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(tren2Label)
                .addGap(1, 1, 1)
                .addComponent(paso2Label)
                .addGap(31, 31, 31)
                .addComponent(seleccioneEstacion2Label)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        paso2Panel.add(jPanel6);

        listaTrenesDisponiblesjTextArea.setEditable(false);
        listaTrenesDisponiblesjTextArea.setColumns(20);
        listaTrenesDisponiblesjTextArea.setRows(5);
        jScrollPane1.setViewportView(listaTrenesDisponiblesjTextArea);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        paso2Panel.add(jPanel7);

        bicicletacheckbox1.setLabel("checkbox1");

        mascotacheckbox2.setLabel("checkbox2");

        bicicletaImagenjLabel.setText("bicicletaImagen");

        mascotajLabel.setText("mascotaImagen");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bicicletacheckbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mascotacheckbox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mascotajLabel)
                    .addComponent(bicicletaImagenjLabel))
                .addContainerGap(323, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bicicletacheckbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bicicletaImagenjLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mascotacheckbox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mascotajLabel))
                .addGap(28, 28, 28))
        );

        paso2Panel.add(jPanel8);

        volver2Button.setText("Volver");

        continuar2Button.setText("Continuar");
        continuar2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuar2ButtonActionPerformed(evt);
            }
        });

        errores2TextField.setText("Comprobacion Errores");
        errores2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errores2TextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(volver2Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 384, Short.MAX_VALUE)
                .addComponent(continuar2Button)
                .addGap(30, 30, 30))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(errores2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(errores2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volver2Button)
                    .addComponent(continuar2Button))
                .addGap(31, 31, 31))
        );

        paso2Panel.add(jPanel9);

        getContentPane().add(paso2Panel, "card3");

        paso3Panel.setEnabled(false);
        paso3Panel.setMaximumSize(new java.awt.Dimension(700, 700));
        paso3Panel.setMinimumSize(new java.awt.Dimension(600, 600));
        paso3Panel.setPreferredSize(new java.awt.Dimension(600, 600));
        paso3Panel.setLayout(new java.awt.GridLayout(2, 1));

        paso3Label.setText("Paso 3");

        seleccioneEstacion3Label.setText("Seleccione las estaciones");

        tren3Label.setText("Tren Castilla y León");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seleccioneEstacion3Label)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(paso3Label))))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tren3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(tren3Label)
                .addGap(10, 10, 10)
                .addComponent(paso3Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seleccioneEstacion3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        paso3Panel.add(jPanel10);

        RadioButton.setText("jRadioButton1");
        RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonActionPerformed(evt);
            }
        });

        volver3Button.setText("Volver");
        volver3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver3ButtonActionPerformed(evt);
            }
        });

        errores3TextField.setText("Comprobacion Errores");
        errores3TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errores3TextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadioButton)
                            .addComponent(volver3Button)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(errores3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(RadioButton)
                .addGap(61, 61, 61)
                .addComponent(errores3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(volver3Button)
                .addGap(49, 49, 49))
        );

        paso3Panel.add(jPanel11);

        getContentPane().add(paso3Panel, "card4");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continuar1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuar1ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_continuar1ButtonActionPerformed

    private void bicicletaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bicicletaComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bicicletaComboBoxActionPerformed

    private void volver3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver3ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volver3ButtonActionPerformed

    private void continuar2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuar2ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_continuar2ButtonActionPerformed

    private void RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonActionPerformed

    private void errores2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errores2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_errores2TextFieldActionPerformed

    private void errores3TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errores3TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_errores3TextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioButton;
    private javax.swing.JComboBox<String> bicicletaComboBox;
    private javax.swing.JLabel bicicletaImagenjLabel;
    private java.awt.Checkbox bicicletacheckbox1;
    private javax.swing.JButton continuar1Button;
    private javax.swing.JButton continuar2Button;
    private javax.swing.JTextField errores1TextField;
    private javax.swing.JTextField errores2TextField;
    private javax.swing.JTextField errores3TextField;
    private javax.swing.JLabel fechaImagenLabel;
    private javax.swing.JSpinner fechaSpinner;
    private javax.swing.JButton intercambiarEstacionesButton;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea listaTrenesDisponiblesjTextArea;
    private javax.swing.JComboBox<String> mascotaComboBox;
    private java.awt.Checkbox mascotacheckbox2;
    private javax.swing.JLabel mascotajLabel;
    private javax.swing.JLabel paso1Label;
    private javax.swing.JPanel paso1Panel;
    private javax.swing.JLabel paso2Label;
    private javax.swing.JPanel paso2Panel;
    private javax.swing.JLabel paso3Label;
    private javax.swing.JPanel paso3Panel;
    private javax.swing.JLabel seleccioneEstacion2Label;
    private javax.swing.JLabel seleccioneEstacion3Label;
    private javax.swing.JLabel seleccioneEstacionLabel;
    private javax.swing.JLabel tren2Label;
    private javax.swing.JLabel tren3Label;
    private javax.swing.JLabel trenLabel;
    private javax.swing.JButton volver2Button;
    private javax.swing.JButton volver3Button;
    // End of variables declaration//GEN-END:variables
}
