package uva.ipc.numberadditionvista;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author danie
 */
public class VistaNA extends javax.swing.JFrame {

    private ControladorNA miControlador;

    /**
     * Creates new form NumberAddition
     */
    public VistaNA() {
        initComponents();
        this.miControlador = new ControladorNA(this);
        this.limpiar();
        this.limpiarError();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        textArea1 = new java.awt.TextArea();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        primerNumeroTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        segundoNumeroTextField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        resultadoNumeroTextField = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        errorLabel = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        sumarButton = new javax.swing.JButton();
        limpiarButton = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));
        jPanel2.add(textArea1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel5.setLayout(new java.awt.GridLayout(5, 1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout1.setAlignOnBaseline(true);
        jPanel1.setLayout(flowLayout1);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(24, 24, 24));
        jLabel1.setText("Primer Número:");
        jPanel1.add(jLabel1);

        primerNumeroTextField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        primerNumeroTextField.setMinimumSize(new java.awt.Dimension(264, 52));
        primerNumeroTextField.setPreferredSize(new java.awt.Dimension(264, 22));
        jPanel1.add(primerNumeroTextField);

        jPanel5.add(jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(24, 24, 24));
        jLabel2.setText("Segundo Número:");
        jPanel3.add(jLabel2);

        segundoNumeroTextField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        segundoNumeroTextField.setMinimumSize(new java.awt.Dimension(264, 52));
        segundoNumeroTextField.setPreferredSize(new java.awt.Dimension(264, 22));
        jPanel3.add(segundoNumeroTextField);

        jPanel5.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout2.setAlignOnBaseline(true);
        jPanel4.setLayout(flowLayout2);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(24, 24, 24));
        jLabel3.setText("Resultado:");
        jPanel4.add(jLabel3);

        resultadoNumeroTextField.setEditable(false);
        resultadoNumeroTextField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        resultadoNumeroTextField.setMinimumSize(new java.awt.Dimension(264, 52));
        resultadoNumeroTextField.setPreferredSize(new java.awt.Dimension(264, 22));
        jPanel4.add(resultadoNumeroTextField);

        jPanel5.add(jPanel4);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        errorLabel.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel.setText("Primer Número:");
        jPanel6.add(errorLabel);

        jPanel5.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        sumarButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        sumarButton.setForeground(new java.awt.Color(24, 24, 24));
        sumarButton.setText("Sumar");
        sumarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumarButtonActionPerformed(evt);
            }
        });
        jPanel7.add(sumarButton);

        limpiarButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        limpiarButton.setForeground(new java.awt.Color(24, 24, 24));
        limpiarButton.setText("Limpiar");
        limpiarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarButtonActionPerformed(evt);
            }
        });
        jPanel7.add(limpiarButton);

        salirButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        salirButton.setForeground(new java.awt.Color(24, 24, 24));
        salirButton.setText("Salir");
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });
        jPanel7.add(salirButton);

        jPanel5.add(jPanel7);

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sumarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumarButtonActionPerformed
        miControlador.eventoSumar();
    }//GEN-LAST:event_sumarButtonActionPerformed


    private void limpiarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarButtonActionPerformed
        miControlador.limpiar();
    }//GEN-LAST:event_limpiarButtonActionPerformed

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        miControlador.salir();
    }//GEN-LAST:event_salirButtonActionPerformed

    public void escribirError(String error) {
        errorLabel.setText(error);
    }

    void limpiar() {
        primerNumeroTextField.setText("");
        segundoNumeroTextField.setText("");
        resultadoNumeroTextField.setText("");
    }

    void limpiarError() {
        errorLabel.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton limpiarButton;
    private javax.swing.JTextField primerNumeroTextField;
    private javax.swing.JTextField resultadoNumeroTextField;
    private javax.swing.JButton salirButton;
    private javax.swing.JTextField segundoNumeroTextField;
    private javax.swing.JButton sumarButton;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables

    String getPrimerNumeroText() {
        return primerNumeroTextField.getText();
    }

    String getSegundoNumeroText() {
        return segundoNumeroTextField.getText();
    }

    void setResultadoText(String res) {
        resultadoNumeroTextField.setText(res);
    }

    void setHistorialText(String newHistorial) {
       textArea1.setText(newHistorial);
    }
}
