/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uva.ipc.vista;

import com.formdev.flatlaf.*;
import com.formdev.flatlaf.intellijthemes.*;
import java.awt.*;
import javax.swing.*;
import uva.ipc.modelo.Viaje;

/**
 * @author Daniel Garcia Solla
 * @author Carolina de las Heras Clavier
 */
public class VistaMenu extends javax.swing.JFrame {

    private ControladorMenu controlador;
    private DefaultListModel<Viaje> viajesListModel = new DefaultListModel<>();
    private boolean darkTheme = false;

    /**
     * Creates new form MainFrame
     */
    public VistaMenu() {
        FlatLaf.setup(new FlatArcOrangeIJTheme());

        this.setIconImage(new ImageIcon("src/main/resources/Tarjetacyl.png").getImage());
        initComponents();
        this.setLocationRelativeTo(null);//Para que no aparezca a arriba a la izquierda
        this.controlador = new ControladorMenu(this);
        setMinimumSize(new Dimension(650, 700));

        styleButtons();
    }

    /**
     * Aplica un estilo específico a una serie de botones.
     */
    public void styleButtons() {
        styleButton(comprarBilleteButton);
        styleButton(accesoTarjetaButton);
    }

    /**
     * Aplica un estilo personalizado a un botón.
     *
     * @param button El botón al que se le aplicará el estilo.
     */
    public void styleButton(JButton button) {
        button.setBackground(UIManager.getColor("Component.accentColor"));
        if (darkTheme) {
            button.setForeground(UIManager.getColor("Label.foreground"));
        } else {
            button.setForeground(UIManager.getColor("Label.background"));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        paso1Panel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        paso1Label = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        comprarBilleteButton = new javax.swing.JButton();
        accesoTarjetaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tren Castilla y León");
        getContentPane().setLayout(new java.awt.CardLayout());

        paso1Panel.setEnabled(false);
        paso1Panel.setMaximumSize(new java.awt.Dimension(700, 700));
        paso1Panel.setMinimumSize(new java.awt.Dimension(600, 600));
        paso1Panel.setPreferredSize(new java.awt.Dimension(600, 600));
        paso1Panel.setLayout(new javax.swing.BoxLayout(paso1Panel, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        paso1Label.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        paso1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paso1Label.setText("Tren CYL");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(52, 223, 60, 220);
        jPanel2.add(paso1Label, gridBagConstraints);

        paso1Panel.add(jPanel2);

        jPanel5.setLayout(new java.awt.GridBagLayout());

        comprarBilleteButton.setBackground(UIManager.getColor("Component.accentColor"));
        comprarBilleteButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comprarBilleteButton.setText("Comprar billete");
        comprarBilleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarBilleteButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 212, 231, 230);
        jPanel5.add(comprarBilleteButton, gridBagConstraints);

        accesoTarjetaButton.setBackground(UIManager.getColor("Component.accentColor"));
        accesoTarjetaButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        accesoTarjetaButton.setText("Acceso con tarjeta");
        accesoTarjetaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accesoTarjetaButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 212, 0, 230);
        jPanel5.add(accesoTarjetaButton, gridBagConstraints);

        paso1Panel.add(jPanel5);

        getContentPane().add(paso1Panel, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Maneja el evento de acción del botón para pasar del paso 1 al 2
     *
     * @param evt
     */
    private void comprarBilleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarBilleteButtonActionPerformed
        controlador.comprarBillete();
    }//GEN-LAST:event_comprarBilleteButtonActionPerformed

    private void accesoTarjetaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accesoTarjetaButtonActionPerformed
        controlador.accesoTarjeta();
    }//GEN-LAST:event_accesoTarjetaButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accesoTarjetaButton;
    private javax.swing.JButton comprarBilleteButton;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel paso1Label;
    private javax.swing.JPanel paso1Panel;
    // End of variables declaration//GEN-END:variables

}//class Vista
